version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8.11.4

      - working_directory: ~/repo

      steps:

        - checkout

        - run: npm install

        - run: cd client && npm install && npm run build

        - run: cd ..

        - run: npm run test

